---
title: "Tidy Data"
output: github_document
---

9/17/2024 The days are getting shorter

9/19/2024 The sun will set

9/24/2024 

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  ) %>% 
  relocate(id, visit)
```

One more example.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", "")) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "weight"
  ) %>% 
  mutate(
    gd_time = case_match (
      gd_time,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```

##Pivot wider

```{r}
analysis_df = 
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```

```{r}
analysis_df %>% 
  pivot_wider(
    names_from = time,
    values_from = mean
  ) %>% 
  knitr::kable()
```






This document will show how to **tidy** data.



This document will show how to **manipulate** data.

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

pups_df = 
  read_csv("data/FAS_pups.csv", na = c("NA", "", "."))

pups_df = janitor::clean_names(pups_df)
```

## 'select'

Use 'select()' to select variables

Note: group names are case-sensitive

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
# select from one column to another
```

```{r}
select(litters_df, -pups_survive)
```

```{r}
select(litters_df, -(group:gd18_weight))
```

```{r}
select(litters_df, starts_with(("gd")))

select(litters_df, contains("pups"))
```

```{r}
select(litters_df, GROUP = group)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, gd0_weight, everything())

relocate(litters_df, litter_number, gd0_weight)
# does the same thing with 'select'
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```



## 'filter'
```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, gd_of_birth == 19)
```

```{r}
filter(litters_df, pups_born_alive > 8)
filter(litters_df, pups_born_alive >= 8)
```

```{r}
filter(litters_df, pups_born_alive != 9)
```

```{r}
filter(litters_df, group == "Low8")
filter(litters_df, group %in% c("Low7", "Low8"))
```

```{r}
filter(litters_df, group %in% c("Low7", "Low8"), pups_born_alive == 8)

# the vertical bar means "or"
filter(litters_df, group %in% c("Low7", "Low8") | pups_born_alive == 8)
```

```{r}
drop_na(litters_df)

drop_na(litters_df, gd0_weight)
```

```{r}
filter(pups_df, sex == 1)

filter(pups_df, pd_walk < 11, sex == 2)
```

## 'mutate'

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, sq_pups = pups_born_alive^2)

# operate on character variables
mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
  )
```

## 'arrange'

```{r}
arrange(litters_df, gd0_weight)

arrange(litters_df, desc(gd0_weight))

arrange(litters_df, pups_born_alive, gd0_weight)
```

## Piping

Don't do this:

```{r}
litters_df = read_csv('data/FAS_litters.csv', na = c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

litters_df_var = select(litters_df, -pups_born_alive)

litters_with_filter = filter(litters_df_var, group == "Con7")

litters_wt_gain = mutate(litters_with_filter, wt_gain = gd18_weight - gd0_weight)
# sucks for reading
```

do this:
*use Ctrl + Shift + M hotkey for the sign %>% *
```{r}
litters_df = 
  read_csv('data/FAS_litters.csv', na = c("NA", "", ".")) %>% 
  janitor::clean_names() %>% 
  select(-pups_born_alive) %>% 
  filter(group == "Con7") %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight
  )
```

```{r}
read_csv("data/FAS_litters.csv", na = c("NA", "", ".")) %>% 
  janitor::clean_names() %>% 
  mutate(
    wt_gain = 
      gd18_weight - gd0_weight,
    group = str_to_lower(group)
    ) %>% 
  select(-pups_born_alive) %>% 
  filter(group == "Con7")

write_csv(litters_df, "data/cleaned_fas_litters.csv")
```



